### PR TITLE
theseus: copy index.d.ts in npm build

### PR DESCRIPTION
**Pull request by uforic**
## Description
I started a create-react-app from scratch, and noticed that types for formula-one weren't being recognized by TypeScript.

I see in the entry for package.json, types should be at src/index.d.ts, but they weren't there in the built npm folder.

First step - move index.d.ts into the src/ root.

Second step - use the --copy-files command in babel to copy non-compiled files (like.d.ts) into the dist folder.

There are probably other ways to solve this, but after running `yarn build` with this PR, index.d.ts appears in the `dist` folder after build.

### CODE REVIEW

**Comment by uforic** [comment]
Now I'm not so sure that the babel --copy-files directive is needed, perhaps just moving the types to the src/ folder is sufficient. Let me know if you need any more deets!

**Comment by uforic** [comment]
@

**Comment by dmnd** [comment]
👋  Hello Matt! Thanks for the PR.

I know @zgotsch was using TS types... somehow. Assigning to him to figure out if this PR needs to merge.

**Comment by uforic** [comment]
👋 howdy!

Roger @dmnd  - the types work great, once in I copy them into my node_modules/formula-one/src folder; maybe I'm doing something wrong, but I suspect there is just a missing "cp" command somewhere in the build/publish phase! But will defer to wizard @zgotsch .

Stoked to use the library!

**Comment by zgotsch** [comment]
Cool! Sorry about this. I support copying the file to `/dist`, since hopefully in the future it will be possible to do something similar with the Flow types and we won't have to ship `/src` to enable that typechecking.

It looks like there have been some formatting changes in the typescript definitions since you branched, so I think it's easier if I just make my own branch. Can you test out `zgotsch/copy_ts_def_to_dist` and let me know if that works for you?

**Comment by uforic** [comment]
Yo! Checked out you branch, ran build, and copied the dist/ folder into my node_modules of my project, along with changing the index.d.ts. Types worked! Thanks!

**Comment by uforic** [comment]
@zgotsch , let me know if you need anything else to get your branch across the finish line!

**Comment by zgotsch** [comment]
Closed in favor of #119. Thanks, @uforic!

**Pull request closed without merging**
